'use strict';

const {
  SlashCommandBuilder,
  PermissionsBitField,
  ChannelType,
  EmbedBuilder,
} = require('discord.js');
const path = require('path');
const fs = require('fs');
const { Colors, FOOTER_TEXT } = require('../../config/colors');
const Guild = require('../../models/Guild');
const { postVerificationPanel } = require('../../systems/verification/verificationPanel');
const { postRoleSelectionPanel } = require('../../systems/roles/roleSelection');
const { postTicketPanel } = require('../../systems/tickets/ticketManager');
const { postBackupBotsPanel } = require('../../systems/bots/backupBots');

// Permission flag map
const PERM_MAP = {
  Administrator: PermissionsBitField.Flags.Administrator,
  ManageMessages: PermissionsBitField.Flags.ManageMessages,
  KickMembers: PermissionsBitField.Flags.KickMembers,
  ModerateMembers: PermissionsBitField.Flags.ModerateMembers,
  ViewAuditLog: PermissionsBitField.Flags.ViewAuditLog,
  ViewChannel: PermissionsBitField.Flags.ViewChannel,
  SendMessages: PermissionsBitField.Flags.SendMessages,
  ReadMessageHistory: PermissionsBitField.Flags.ReadMessageHistory,
  UseExternalEmojis: PermissionsBitField.Flags.UseExternalEmojis,
  AddReactions: PermissionsBitField.Flags.AddReactions,
  AttachFiles: PermissionsBitField.Flags.AttachFiles,
  EmbedLinks: PermissionsBitField.Flags.EmbedLinks,
  Connect: PermissionsBitField.Flags.Connect,
  Speak: PermissionsBitField.Flags.Speak,
};

/**
 * Sleep helper for rate limit protection
 */
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/**
 * Build a visual progress bar string
 * @param {number} current - Current step (1-indexed)
 * @param {number} total - Total steps
 * @returns {string}
 */
function buildProgressBar(current, total) {
  const filled = Math.round((current / total) * 10);
  const empty = 10 - filled;
  const bar = '█'.repeat(filled) + '░'.repeat(empty);
  const pct = Math.round((current / total) * 100);
  return `\`[${bar}] ${pct}%\``;
}

/**
 * Post a rich getting-started guide embed
 * @param {import('discord.js').TextChannel} channel
 * @param {import('discord.js').Guild} guild
 * @param {Object} channelMap
 * @param {Object} roles
 */
async function postGettingStarted(channel, guild, channelMap, roles) {
  const embed = new EmbedBuilder()
    .setColor(Colors.PRIMARY)
    .setTitle(`🚀 Welcome to ${guild.name}! Here's How to Get Started`)
    .setDescription(
      [
        '> **Follow these steps in order and you\'ll be all set in under 2 minutes!**',
        '',
        '**Step 1 — ✅ Verify Yourself**',
        `> Head to <#${channelMap['verify'] || ''}> and click the **Verify** button.`,
        '> This gives you the **Member** role and unlocks all channels.',
        '',
        '**Step 2 — 🎭 Pick Your Roles**',
        `> Go to <#${channelMap['roleSelection'] || ''}> and select:`,
        '> • 🔪 **Killer Main** or 💚 **Survivor Main** (DBD)',
        '> • 🤠 **Cowgirl** (RDR2)',
        '> • 💕 **Girls Chat** (unlocks private channel)',
        '',
        '**Step 3 — 📜 Read the Rules**',
        `> Check <#${channelMap['rules'] || ''}> so you know what\'s allowed.`,
        '> Breaking rules results in: **Warn → Timeout → Kick → Ban**',
        '',
        '**Step 4 — 👋 Introduce Yourself**',
        `> Say hi in <#${channelMap['introductions'] || ''}> and tell us about yourself!`,
        '',
        '**Step 5 — 🎮 Dive In!**',
        `> Chat in <#${channelMap['generalChat'] || ''}>, discuss DBD, share clips, and have fun!`,
        '',
        '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
        '',
        '**🆘 Need Help?**',
        `> Open a ticket in the 🎫 ticket channel`,
        '> DM the bot directly for modmail',
        '',
        '*We\'re glad you\'re here! Enjoy the community! 🎉*',
      ].join('\n')
    )
    .setThumbnail(guild.iconURL({ dynamic: true }))
    .setFooter({ text: `${guild.name} • Auto-generated by setup system` })
    .setTimestamp();

  await channel.send({ embeds: [embed] });
}

/**
 * Find or create a role by name, deduplication-safe
 * @param {import('discord.js').Guild} guild
 * @param {Object} roleDef
 * @returns {Promise<import('discord.js').Role>}
 */
async function findOrCreateRole(guild, roleDef) {
  const existing = guild.roles.cache.find(
    (r) => r.name.toLowerCase() === roleDef.name.toLowerCase()
  );
  if (existing) return existing;

  const perms = (roleDef.permissions || []).reduce((acc, p) => {
    if (PERM_MAP[p]) acc |= PERM_MAP[p];
    return acc;
  }, 0n);

  const role = await guild.roles.create({
    name: roleDef.name,
    color: roleDef.color || '#99AAB5',
    hoist: roleDef.hoist || false,
    permissions: perms,
    reason: 'Community Setup',
  });

  await sleep(300); // rate limit guard
  return role;
}

/**
 * Find or create a channel by name in a parent, deduplication-safe
 */
async function findOrCreateChannel(guild, name, type, parentId, overwrites, topic) {
  const existing = guild.channels.cache.find(
    (c) => c.name.toLowerCase() === name.toLowerCase() && c.parentId === parentId
  );
  if (existing) return existing;

  const opts = {
    name,
    type,
    reason: 'Community Setup',
  };
  if (parentId) opts.parent = parentId;
  if (overwrites) opts.permissionOverwrites = overwrites;
  if (topic && type === ChannelType.GuildText) opts.topic = topic;

  const ch = await guild.channels.create(opts);
  await sleep(400); // rate limit guard
  return ch;
}

/**
 * Generate permission overwrites for a category/channel
 * @param {import('discord.js').Guild} guild
 * @param {string} permType
 * @param {Object} roles - name→role map
 * @returns {Array}
 */
function buildPermissionOverwrites(guild, permType, roles) {
  const everyone = guild.roles.everyone;

  switch (permType) {
    case 'readonly':
      return [
        { id: everyone.id, allow: [PermissionsBitField.Flags.ViewChannel], deny: [PermissionsBitField.Flags.SendMessages] },
        ...(roles['Admin'] ? [{ id: roles['Admin'].id, allow: [PermissionsBitField.Flags.SendMessages] }] : []),
        ...(roles['Moderator'] ? [{ id: roles['Moderator'].id, allow: [PermissionsBitField.Flags.SendMessages] }] : []),
      ];

    case 'announcements':
      return [
        { id: everyone.id, allow: [PermissionsBitField.Flags.ViewChannel], deny: [PermissionsBitField.Flags.SendMessages] },
        ...(roles['Admin'] ? [{ id: roles['Admin'].id, allow: [PermissionsBitField.Flags.SendMessages] }] : []),
      ];

    case 'staffOnly':
      return [
        { id: everyone.id, deny: [PermissionsBitField.Flags.ViewChannel] },
        ...(roles['Admin'] ? [{ id: roles['Admin'].id, allow: [PermissionsBitField.Flags.ViewChannel, PermissionsBitField.Flags.SendMessages] }] : []),
        ...(roles['Moderator'] ? [{ id: roles['Moderator'].id, allow: [PermissionsBitField.Flags.ViewChannel, PermissionsBitField.Flags.SendMessages] }] : []),
        ...(roles['Trial Moderator'] ? [{ id: roles['Trial Moderator'].id, allow: [PermissionsBitField.Flags.ViewChannel, PermissionsBitField.Flags.SendMessages] }] : []),
      ];

    case 'girlsOnly':
      return [
        { id: everyone.id, deny: [PermissionsBitField.Flags.ViewChannel] },
        ...(roles['Girls Chat'] ? [{ id: roles['Girls Chat'].id, allow: [PermissionsBitField.Flags.ViewChannel, PermissionsBitField.Flags.SendMessages] }] : []),
        ...(roles['Admin'] ? [{ id: roles['Admin'].id, allow: [PermissionsBitField.Flags.ViewChannel] }] : []),
        ...(roles['Moderator'] ? [{ id: roles['Moderator'].id, allow: [PermissionsBitField.Flags.ViewChannel] }] : []),
      ];

    case 'verify':
      return [
        { id: everyone.id, allow: [PermissionsBitField.Flags.ViewChannel, PermissionsBitField.Flags.ReadMessageHistory], deny: [PermissionsBitField.Flags.SendMessages] },
      ];

    default: // 'default'
      return [];
  }
}

/**
 * Post the rules embed
 * @param {import('discord.js').TextChannel} channel
 * @param {import('discord.js').Guild} guild
 */
async function postRulesEmbed(channel, guild) {
  const embed = new EmbedBuilder()
    .setColor(Colors.PRIMARY)
    .setTitle(`📜 ${guild.name} — Server Rules`)
    .setDescription(
      [
        '**Welcome to our community! Please follow these rules:**',
        '',
        '**1. 🤝 Be Respectful**',
        '> Treat everyone with respect. No harassment, hate speech, or discrimination of any kind.',
        '',
        '**2. 🚫 No Spam**',
        '> Do not spam messages, emojis, or commands. Avoid mass tagging.',
        '',
        '**3. 🔞 Age-Appropriate Content**',
        '> No NSFW content outside of designated channels. Keep content suitable for all ages.',
        '',
        '**4. 🔗 No Unauthorized Links/Ads**',
        '> No advertising, self-promotion, or Discord invite links without staff permission.',
        '',
        '**5. 🎮 Stay On Topic**',
        '> Keep conversations relevant to the channel topic.',
        '',
        '**6. 🌍 English Only**',
        '> Please communicate in English in general channels.',
        '',
        '**7. 🛡 Follow Discord ToS**',
        '> All Discord Terms of Service apply here. [Read them here](https://discord.com/terms)',
        '',
        '**8. 🎫 Use Tickets for Issues**',
        '> Do not DM staff for help. Use the ticket system.',
        '',
        '*Breaking rules may result in: Warning → Timeout → Kick → Ban*',
      ].join('\n')
    )
    .setThumbnail(guild.iconURL({ dynamic: true }))
    .setFooter({ text: FOOTER_TEXT })
    .setTimestamp();

  await channel.send({ embeds: [embed] });
}

/**
 * Post the FAQ embed
 */
async function postFAQEmbed(channel) {
  const embed = new EmbedBuilder()
    .setColor(Colors.PRIMARY)
    .setTitle('❓ Frequently Asked Questions')
    .addFields(
      { name: '🎮 What games does this server focus on?', value: 'Dead By Daylight and Red Dead Redemption 2!' },
      { name: '✅ How do I get full access?', value: 'Go to `#verify` and click the Verify button.' },
      { name: '🎭 How do I get game roles?', value: 'Visit `#role-selection` to pick your roles.' },
      { name: '💕 How do I access Girls Chat?', value: 'Select the Girls Chat role in `#role-selection`.' },
      { name: '🎫 How do I contact staff?', value: 'Open a ticket in the ticket channel or DM the bot for modmail.' },
      { name: '🚨 How do I report someone?', value: 'Create a Report ticket or DM the bot with evidence.' }
    )
    .setFooter({ text: FOOTER_TEXT })
    .setTimestamp();

  await channel.send({ embeds: [embed] });
}

module.exports = {
  data: new SlashCommandBuilder()
    .setName('setup')
    .setDescription('🛠️ Complete server setup — creates all channels, roles, and systems')
    .setDefaultMemberPermissions(PermissionsBitField.Flags.Administrator),

  async execute(interaction) {
    const { guild, member } = interaction;

    // Permission check
    if (!member.permissions.has(PermissionsBitField.Flags.Administrator)) {
      return interaction.reply({
        content: '❌ You need Administrator permissions to run setup.',
        ephemeral: true,
      });
    }

    await interaction.reply({
      embeds: [
        new EmbedBuilder()
          .setColor(Colors.ERROR)
          .setTitle('💥 Community Setup — Full Reset')
          .setDescription(
            [
              '> ⚠️ **This will delete ALL existing channels and roles, then rebuild from scratch.**',
              '',
              '**What happens next:**',
              '> 💥 Step 0 — Nuke all existing channels & roles',
              '> 🎭 Step 1 — Create 13 roles with colors and hierarchy',
              '> 📁 Step 2 — Create 10 categories and 30+ channels',
              '> 🎫 Step 3 — Build the ticket system',
              '> 💾 Step 4 — Save config to database',
              '> 📋 Step 5 — Post getting-started, rules, and FAQ',
              '> 🔘 Step 6 — Post verification, roles, and ticket panels',
              '> 🤖 Step 7 — Post backup bot dashboard (staff only)',
              '> 🎭 Step 8 — Lock down @everyone permissions',
              '> ✅ Step 9 — Done!',
              '',
              '⏳ **Please wait 2-3 minutes. Do not run the command again.**',
            ].join('\n')
          )
          .setFooter({ text: FOOTER_TEXT })
          .setTimestamp(),
      ],
      ephemeral: true,
    });

    const TOTAL_STEPS = 9;
    const progressUpdate = async (step, title, details) => {
      await interaction.editReply({
        embeds: [
          new EmbedBuilder()
            .setColor(Colors.PRIMARY)
            .setTitle(`⚙️ Setup In Progress — Step ${step} of ${TOTAL_STEPS}`)
            .setDescription(
              [
                buildProgressBar(step, TOTAL_STEPS),
                '',
                `**${title}**`,
                details,
              ].join('\n')
            )
            .setFooter({ text: `${FOOTER_TEXT} | Do NOT close Discord or run /setup again` })
            .setTimestamp(),
        ],
      }).catch(() => {});
    };

    try {
      // Load template
      const templatePath = path.join(process.cwd(), 'templates', 'dbd-community.json');
      const template = JSON.parse(fs.readFileSync(templatePath, 'utf-8'));
      const totalChannels = template.categories.reduce((a, c) => a + c.channels.length, 0);

      // ────────────────────────────────────────────────────────────────────────
      // STEP 0: NUKE — Delete all channels and roles (clean slate)
      // ────────────────────────────────────────────────────────────────────────
      await progressUpdate(0, '💥 Nuking Server',
        '> Deleting all existing channels and roles...\n> *(This is safe — everything will be rebuilt fresh)*'
      );

      // Fetch fresh channel & role lists
      await guild.channels.fetch();
      await guild.roles.fetch();

      // Delete all channels
      const channelDeletePromises = guild.channels.cache.map(async (ch) => {
        try {
          await ch.delete('Setup nuke — clearing server');
          await sleep(300);
        } catch (_) { /* bot can't delete its own interaction channel, skip */ }
      });
      await Promise.allSettled(channelDeletePromises);

      await sleep(1000); // extra buffer after bulk channel deletes

      // Delete all deletable roles (skip @everyone, bot-managed, and higher roles)
      const botMember = guild.members.me;
      const botHighestPos = botMember?.roles?.highest?.position ?? 0;

      const rolesToDelete = guild.roles.cache.filter(
        (r) =>
          r.id !== guild.roles.everyone.id &&
          !r.managed &&
          r.position < botHighestPos
      );

      for (const [, role] of rolesToDelete) {
        try {
          await role.delete('Setup nuke — clearing roles');
          await sleep(300);
        } catch (_) { /* skip undeletable roles */ }
      }

      await sleep(1000); // buffer after role deletes

      await progressUpdate(1, '🎭 Creating Roles',
        `> Building ${template.roles.length} roles with colors and hierarchy...\n> Owner → Admin → Moderator → Member`
      );

      // ────────────────────────────────────────────────────────────────────────
      // STEP 1: Create Roles
      // ────────────────────────────────────────────────────────────────────────
      const roles = {};
      for (const roleDef of template.roles) {
        roles[roleDef.name] = await findOrCreateRole(guild, roleDef);
        await sleep(200);
      }

      await progressUpdate(2, '📁 Creating Channels',
        `> Building ${template.categories.length} categories and ${totalChannels} channels...\n> Setting permissions, topics, and overwrites`
      );

      // ────────────────────────────────────────────────────────────────────────
      // STEP 2: Create Categories & Channels
      // ────────────────────────────────────────────────────────────────────────
      const channelMap = {};
      let ticketCategoryId = null;

      for (const cat of template.categories) {
        // Create or find category
        const existingCat = guild.channels.cache.find(
          (c) => c.name.toLowerCase() === cat.name.toLowerCase() && c.type === ChannelType.GuildCategory
        );
        const catOverwrites = buildPermissionOverwrites(guild, cat.permissions, roles);

        let category;
        if (existingCat) {
          category = existingCat;
        } else {
          category = await guild.channels.create({
            name: cat.name,
            type: ChannelType.GuildCategory,
            permissionOverwrites: catOverwrites,
            reason: 'Community Setup',
          });
          await sleep(400);
        }

        // Create channels under category
        for (const chDef of cat.channels) {
          const chType = chDef.type === 'voice' ? ChannelType.GuildVoice : ChannelType.GuildText;
          const chOverwrites = chDef.permissions
            ? buildPermissionOverwrites(guild, chDef.permissions, roles)
            : null;

          const ch = await findOrCreateChannel(
            guild,
            chDef.name,
            chType,
            category.id,
            chOverwrites,
            chDef.topic
          );

          if (chDef.key) channelMap[chDef.key] = ch.id;
        }
      }

      await progressUpdate(3, '🎫 Building Ticket System',
        '> Creating ticket category and panel channel...\n> Support, Bug Report, Appeal, and Partnership types'
      );

      // ────────────────────────────────────────────────────────────────────────
      // STEP 3: Ticket Category
      // ────────────────────────────────────────────────────────────────────────
      const existingTicketCat = guild.channels.cache.find(
        (c) => c.name.toLowerCase() === '🎫 tickets' && c.type === ChannelType.GuildCategory
      );

      let ticketCategory;
      if (existingTicketCat) {
        ticketCategory = existingTicketCat;
      } else {
        ticketCategory = await guild.channels.create({
          name: '🎫 TICKETS',
          type: ChannelType.GuildCategory,
          permissionOverwrites: [
            { id: guild.roles.everyone.id, deny: [PermissionsBitField.Flags.ViewChannel] },
          ],
          reason: 'Community Setup',
        });
        await sleep(400);
      }

      ticketCategoryId = ticketCategory.id;

      // Ticket panel channel
      const ticketPanelCh = await findOrCreateChannel(
        guild,
        '🎫-tickets',
        ChannelType.GuildText,
        null,
        [],
        'Open a support ticket here.'
      );
      channelMap['tickets'] = ticketPanelCh.id;

      await progressUpdate(4, '💾 Saving Configuration',
        '> Storing channel IDs, role IDs, and settings to database...\n> Enabling AutoMod, logging, and protection systems'
      );

      // ────────────────────────────────────────────────────────────────────────
      // STEP 4: Save to DB
      // ────────────────────────────────────────────────────────────────────────
      const roleMap = {
        owner: roles['Owner']?.id,
        admin: roles['Admin']?.id,
        moderator: roles['Moderator']?.id,
        trialModerator: roles['Trial Moderator']?.id,
        dbdVeteran: roles['DBD Veteran']?.id,
        survivorMain: roles['Survivor Main']?.id,
        killerMain: roles['Killer Main']?.id,
        cowgirl: roles['Cowgirl']?.id,
        girlsChat: roles['Girls Chat']?.id,
        booster: roles['Booster']?.id,
        verified: roles['Verified']?.id,
        member: roles['Member']?.id,
        newMember: roles['New Member']?.id,
      };

      await Guild.findOneAndUpdate(
        { guildId: guild.id },
        {
          guildId: guild.id,
          setupComplete: true,
          setupAt: new Date(),
          channels: channelMap,
          roles: roleMap,
          ticketCategoryId,
          automod: {
            enabled: true,
            antiSpam: true,
            antiRaid: true,
            antiLink: true,
            antiScam: true,
            massMention: true,
            excessiveCaps: true,
            logChannelId: channelMap['logs'] || null,
          },
        },
        { upsert: true, new: true }
      );

      await progressUpdate(5, '📋 Posting Information Panels',
        '> Writing getting-started guide, rules, and FAQ...\n> Members will see these when they first join'
      );

      // Getting Started
      if (channelMap['gettingStarted']) {
        const gsCh = guild.channels.cache.get(channelMap['gettingStarted']);
        if (gsCh) await postGettingStarted(gsCh, guild, channelMap, roles);
      }

      await sleep(500);

      // Rules
      if (channelMap['rules']) {
        const rulesCh = guild.channels.cache.get(channelMap['rules']);
        if (rulesCh) await postRulesEmbed(rulesCh, guild);
      }

      await sleep(500);

      // FAQ
      if (channelMap['faq']) {
        const faqCh = guild.channels.cache.get(channelMap['faq']);
        if (faqCh) await postFAQEmbed(faqCh);
      }

      await sleep(500);

      await progressUpdate(6, '🔘 Setting Up Interactive Panels',
        '> Posting verification button, role selection menu, and ticket panel...\n> Members can click these to verify, get roles, and open tickets'
      );

      // Verification Panel
      if (channelMap['verify']) {
        const verifyCh = guild.channels.cache.get(channelMap['verify']);
        if (verifyCh) await postVerificationPanel(verifyCh, guild);
      }

      await sleep(500);

      // Role Selection Panel
      if (channelMap['roleSelection']) {
        const roleCh = guild.channels.cache.get(channelMap['roleSelection']);
        if (roleCh) await postRoleSelectionPanel(roleCh, guild);
      }

      await sleep(500);

      // Ticket Panel
      if (channelMap['tickets']) {
        const ticketCh = guild.channels.cache.get(channelMap['tickets']);
        if (ticketCh) await postTicketPanel(ticketCh, guild);
      }

      await sleep(500);

      await progressUpdate(7, '🤖 Setting Up Bot Dashboard',
        '> Posting backup bot invite links to staff #bot-dashboard...\n> These bots protect the server if this bot goes offline'
      );

      // Backup bots dashboard (staff-only channel)
      if (channelMap['botDashboard']) {
        const botDashCh = guild.channels.cache.get(channelMap['botDashboard']);
        if (botDashCh) await postBackupBotsPanel(botDashCh, guild);
      }

      await sleep(500);

      await progressUpdate(8, '🎭 Finalizing Permissions',
        '> Locking down @everyone to minimal permissions...\n> Members need the Verified role to access channels'
      );
      await guild.roles.everyone.setPermissions([
        PermissionsBitField.Flags.ViewChannel,
        PermissionsBitField.Flags.ReadMessageHistory,
      ]).catch(() => {});

      await sleep(300);

      await progressUpdate(9, '✅ Almost Done!',
        '> Sending final confirmation and cleaning up...'
      );

      await sleep(500);

      const summaryEmbed = new EmbedBuilder()
        .setColor(Colors.SUCCESS)
        .setTitle('🎉 Server Setup Complete!')
        .setDescription(
          [
            `**${guild.name}** has been fully configured from scratch!`,
            '',
            '**📊 What was built:**',
            `> 🎭 **${template.roles.length} Roles** — Owner, Admin, Mods, Members, Game roles`,
            `> 📁 **${template.categories.length + 1} Categories** — Info, Onboarding, Gaming, Community, Staff, Tickets`,
            `> 📝 **${totalChannels + 1} Channels** — including #getting-started and #bot-dashboard`,
            '',
            '**🤖 Systems now active:**',
            '> ✅ Verification — button panel in #verify',
            '> 🎭 Role selection — menu in #role-selection',
            '> 🎫 Tickets — 4 ticket types in #🎫-tickets',
            '> 🤖 AutoMod — anti-spam, anti-scam, anti-raid, caps, mentions',
            '> 📬 Modmail — members DM the bot, appears in #modmail',
            '> 📋 Logging — joins, bans, edits logged to #logs',
            '> 🎨 Welcome cards — Canvas card for every new member',
            '> 🛡️ Backup bots — invite links posted in staff #bot-dashboard',
            '',
            '**⚠️ Your next steps:**',
            '> **1.** Give yourself the **Owner** role',
            '> **2.** Visit **#bot-dashboard** and invite **Wick** (anti-nuke protection)',
            '> **3.** Set your server icon, banner, and description',
            '> **4.** Announce the server is open in **#announcements**',
            '',
            '*Your server is live and ready! 🎉*',
          ].join('\n')
        )
        .setThumbnail(guild.iconURL({ dynamic: true }))
        .setFooter({ text: FOOTER_TEXT })
        .setTimestamp();

      await interaction.editReply({ embeds: [summaryEmbed] });

      // Log to logs channel
      if (channelMap['logs']) {
        const logsCh = guild.channels.cache.get(channelMap['logs']);
        if (logsCh) {
          await logsCh.send({
            embeds: [
              new EmbedBuilder()
                .setColor(Colors.SUCCESS)
                .setTitle('⚙️ Server Setup Completed')
                .addFields(
                  { name: '👤 Run by', value: `${member.user.tag} (${member.user.id})`, inline: true },
                  { name: '🎭 Roles created', value: `${template.roles.length}`, inline: true },
                  { name: '📁 Channels created', value: `${totalChannels + 1}`, inline: true }
                )
                .setTimestamp(),
            ],
          });
        }
      }
    } catch (err) {
      console.error('[Setup] Error:', err);
      await interaction.editReply({
        embeds: [
          new EmbedBuilder()
            .setColor(Colors.ERROR)
            .setTitle('❌ Setup Failed')
            .setDescription(
              [
                'An error occurred during setup.',
                `**Error:** ${err.message}`,
                '',
                'The setup may be partially complete. Try running `/setup` again — it will skip already-created channels and roles.',
              ].join('\n')
            )
            .setFooter({ text: FOOTER_TEXT })
            .setTimestamp(),
        ],
      });
    }
  },
};
